version: '2.4'

networks:
  vnet-saga-simple-1:

services:
  mariadb-service:
    image: mariadb:10.4
    container_name: mariadbsrv
    hostname: mariadbsrv
    networks:
      - vnet-saga-simple-1
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=htgrfedw
      - MYSQL_DATABASE=sagasimple1
      - MYSQL_USER=sagau
      - MYSQL_PASSWORD=sagahtgrfe
    healthcheck:
      test: mysqladmin --connect_timeout=3 status -h localhost -u sagau -psagahtgrfe
      interval: 7s
      retries: 10
  activemq-service:
    build:
      context: activemq/
      dockerfile: Dockerfile
    image: saga-tests-simple-1/activemq:5.15.9
    container_name: activemqsrv
    hostname: activemqsrv
    networks:
      - vnet-saga-simple-1
    ports:
      - 8161:8161
    healthcheck:
      test: curl -u admin:admin -s http://localhost:8161/api/jolokia/exec/org.apache.activemq:type=Broker,brokerName=localhost,service=Health/healthStatus
      interval: 7s
      retries: 10
  order-service:
    image: saga-tests-simple-1/order-service:1.0-NEST-TRANS
    container_name: order-service
    depends_on:
      mariadb-service:
        condition: service_healthy
      activemq-service:
        condition: service_healthy
    hostname: order-service
    networks:
      - vnet-saga-simple-1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadbsrv:3306/sagasimple1
      - SPRING_DATASOURCE_USERNAME=sagau
      - SPRING_DATASOURCE_PASSWORD=sagahtgrfe
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemqsrv:61616
      - SPRING_JMS_REDELIVERY_POLICY_MAXIMUM_REDELIVERIES=300
#      - logging.level.org.hibernate=WARN
  reservation-service:
    image: saga-tests-simple-1/reservation-service:1.0-NEST-TRANS
    container_name: reservation-service
    depends_on:
      mariadb-service:
        condition: service_healthy
      activemq-service:
        condition: service_healthy
    hostname: reservation-service
    networks:
      - vnet-saga-simple-1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadbsrv:3306/sagasimple1
      - SPRING_DATASOURCE_USERNAME=sagau
      - SPRING_DATASOURCE_PASSWORD=sagahtgrfe
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemqsrv:61616
      - SPRING_JMS_REDELIVERY_POLICY_MAXIMUM_REDELIVERIES=300
#      - logging.level.org.hibernate=WARN
  cart-service:
    image: saga-tests-simple-1/cart-service:1.0-NEST-TRANS
    container_name: cart-service
    depends_on:
      mariadb-service:
        condition: service_healthy
      activemq-service:
        condition: service_healthy
    hostname: cart-service
    networks:
      - vnet-saga-simple-1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadbsrv:3306/sagasimple1
      - SPRING_DATASOURCE_USERNAME=sagau
      - SPRING_DATASOURCE_PASSWORD=sagahtgrfe
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemqsrv:61616
      - SPRING_JMS_REDELIVERY_POLICY_MAXIMUM_REDELIVERIES=300
#      - logging.level.org.springframework=DEBUG
