spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://mariadbsrv:3306/sagasimple1
#    username: sagau
#    password: sagahtgrfe
  jpa:
    hibernate:
      ddl-auto: update

#  activemq:
#    broker-url: tcp://activemqsrv:61616
#    user: admin
#    password: admin