spring:
  jta:
    enabled: true
    atomikos:
      properties:
        transaction-manager-unique-name: cart-service-tm
        enable-logging: true
        max-actives: 100
        default-jta-timeout: 300s
        serial-jta-transactions: false

      datasource:
        xa-data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
        min-pool-size: 2
        max-pool-size: 20
        test-query: SELECT 1;

      connectionfactory:
        min-pool-size: 1
        max-pool-size: 20

  jms:
    template:
      time-to-live: 1h

  activemq:
    pool:
      enabled: true
      max-connections: 20
    packages:
      trust-all: true

  jpa:
    hibernate:
      ddl-auto: update
